# Generated by Django 3.1.7 on 2021-03-31 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0004_tarjeta_rfc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('nombre_corto', models.CharField(max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name='movimiento',
            name='cantidad_original',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.CreateModel(
            name='PagoPendiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_original', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('estatus', models.SmallIntegerField(choices=[(0, 'Pendiente'), (1, 'Pagado'), (2, 'Programado')], default=0)),
                ('concepto', models.CharField(max_length=250, null=True)),
                ('programacion', models.CharField(max_length=10)),
                ('pago_automatico', models.BooleanField(default=False)),
                ('periodicidad', models.CharField(max_length=5)),
                ('pago_unico', models.BooleanField(default=False)),
                ('moneda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cat.moneda')),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cat.tarjeta')),
            ],
        ),
        migrations.AddField(
            model_name='movimiento',
            name='moneda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cat.moneda'),
        ),
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor', models.DecimalField(decimal_places=10, max_digits=15)),
                ('moneda_objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversiones_objetivo', to='cat.moneda')),
                ('moneda_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversiones_origen', to='cat.moneda')),
            ],
            options={
                'unique_together': {('moneda_objetivo', 'moneda_origen')},
            },
        ),
    ]
