# Generated by Django 3.1.7 on 2021-03-31 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0005_auto_20210330_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagopendiente',
            name='tarjeta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_pendientes', to='cat.tarjeta'),
        ),
    ]
