# Generated by Django 3.1.7 on 2021-04-20 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0006_auto_20210330_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Monto pagado'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='cantidad_original',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Monto a pagar'),
        ),
        migrations.AlterField(
            model_name='pagopendiente',
            name='cantidad_original',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Monto a pagar'),
        ),
        migrations.CreateModel(
            name='AbonoPendiente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_original', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Monto a pagar')),
                ('estatus', models.SmallIntegerField(choices=[(0, 'Pendiente'), (1, 'Pagado'), (2, 'Programado')], default=0)),
                ('concepto', models.CharField(max_length=250, null=True)),
                ('programacion', models.CharField(max_length=10)),
                ('pago_automatico', models.BooleanField(default=False)),
                ('periodicidad', models.CharField(max_length=5)),
                ('pago_unico', models.BooleanField(default=False)),
                ('parcializable', models.BooleanField(default=False)),
                ('moneda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cat.moneda')),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos_pendientes', to='cat.tarjeta')),
            ],
        ),
        migrations.AddField(
            model_name='movimiento',
            name='abono_pendiente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cat.abonopendiente'),
        ),
    ]
