# Generated by Django 3.2 on 2021-04-26 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0007_auto_20210420_1656'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='archivos/')),
            ],
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='adjunto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cat.archivo'),
        ),
    ]
